/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ServiceRequest {
  'id' : bigint,
  'status' : string,
  'issueDescription' : string,
  'name' : string,
  'email' : string,
  'timestamp' : Time,
  'deviceType' : string,
  'phone' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllServiceRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getServiceRequest' : ActorMethod<[bigint], ServiceRequest>,
  'submitServiceRequest' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'updateRequestStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];