/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ServiceRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'issueDescription' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'deviceType' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getServiceRequest' : IDL.Func([IDL.Nat], [ServiceRequest], ['query']),
  'submitServiceRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateRequestStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ServiceRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'issueDescription' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'deviceType' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getServiceRequest' : IDL.Func([IDL.Nat], [ServiceRequest], ['query']),
    'submitServiceRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateRequestStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };